# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'RWTFlickrSearch' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RWTFlickrSearch
  pod 'ReactiveCocoa', '2.1.8'
  pod 'objectiveflickr', '2.0.4'
  pod 'LinqToObjectiveC', '2.0.0'
  pod 'SDWebImage', '3.7'

  target 'RWTFlickrSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
