# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'SimpleWeather' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleWeather
  pod 'Mantle', '1.3.1'
  pod 'LBBlurredImage', '0.1.0'
  pod 'TSMessages', '0.9.4'
  pod 'ReactiveCocoa', '2.1.6'

end
